# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="robbyrussell"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
CASE_SENSITIVE="true"

# Comment this out to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how many often would you like to wait before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git)

source $ZSH/oh-my-zsh.sh

# Customize to your needs...
export PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/sbin
export PATH=/usr/local/texlive/2012/bin/universal-darwin:$PATH
export PATH=~/bin:$PATH
export PATH=/usr/local/share/npm/bin:$PATH

unsetopt correct_all

[[ $TERM == eterm-color ]] && export TERM=xterm

export VIRTUALENVWRAPPER_PYTHON=/usr/local/bin/python3
export WORKON_HOME=$HOME/.virtualenvs
export PROJECT_HOME=$HOME/Devel
source /usr/local/bin/virtualenvwrapper.sh

# gitignore.io
function gi() { curl http://www.gitignore.io/api/$@ ;}

export PATH=/usr/local/texlive/2014/bin/x86_64-darwin:~/Library/Haskell/bin:$PATH

export DOCKER_HOST=tcp://192.168.59.104:2376
export DOCKER_TLS_VERIFY=1
export DOCKER_CERT_PATH=/Users/walter/.boot2docker/certs/boot2docker-vm

function acurl()
{
    curl -k -H "Authorization: Bearer $TOKEN" https://api.araport.org/community/v0.3$@
}

alias clean_containers="docker ps -aq|xargs docker rm -f"
